### ISSUE TITLE
ex6 compatable

### ISSUE THREAD

**Issue by jawetzel** [Azure-Samples/SpeechToText-WebSockets-Javascript#10]
any plans to make the SDK compatable with es6 for SPA usage?

**Comment by RaviPidaparthi** [comment]
Do you mean single page applications ? 
The sdk is written is typescript and transpiles to es5 JavaScript so that it wiill be compatible with maximum browsers out there.

Can you let us know the problem you are facing with integration ?

**Comment by jawetzel** [comment]
I'm trying to convert a natural landuage stack from IBM to microsoft with an app built in reactJS, and am trying to get the websocket Speech to text working

**Comment by RaviPidaparthi** [comment]
This library should work just like any other javascript library out there. We have had other people integrate it successfully before.

Can you expand a bit more about the issues you are facing ?

**Comment by jawetzel** [comment]
I think were going to just be starting the project over in typescript

**Comment by RaviPidaparthi** [comment]
Ok. If you use the PM package it comes bundled with definition files as well which would work nicely for typescript development. 

I am closing this issue. Let us know if you see any issues down the line.
