### ISSUE TITLE
Return only the result of: "DisplayText":

### ISSUE THREAD

**Issue by tftoledo** [Azure-Samples/SpeechToText-WebSockets-Javascript#11]
How do I get the "DisplayText" content as a result: instead of all this:

{
"RecognitionStatus": "Success",
"DisplayText": "Test.",
"Offset": 7000000,
"Duration": 42800000
}

**For example, I would like to get: Test.**

**Comment by RaviPidaparthi** [comment]
The sdk does not have a way of giving out just the displaytext. You can use event.Result.DisplayText to display in your UI.

**Comment by RaviPidaparthi** [comment]
I am closing this as this wont be something the sdk will support.
