### ISSUE TITLE
Doesn't work at all in IE or Chrome

### ISSUE THREAD

**Issue by trzy** [Azure-Samples/SpeechToText-WebSockets-Javascript#13]
In Chrome (58.0.3029.110), when I enter the license key I can press 'Start' but it immediately stops before I can even record anything (Chrome asks for permission to use the mic each time, which I grant).  In Internet Explorer (11.198.14393.0), it doesn't work at all -- the Start button is grayed out.

Note that I also had to change line 67 of Sample.html to add 'http:' at the beginning of the require.js URL.

I really wanted to test out this API ASAP. :(

**Comment by RaviPidaparthi** [comment]
I just updated the Readme with Browser support section and the proper way to use the Sample.

To summarize, it is recommended that you load the sample on Https as certain browsers don't support microphone access on un-secure domains. IE is not a supported browser. You can however use any modern browser like Edge/Firefox/Chrome.

I also provided a link to the sample which can directly use to test.
