### ISSUE TITLE
Restar speech recognition

### ISSUE THREAD

**Issue by tftoledo** [Azure-Samples/SpeechToText-WebSockets-Javascript#15]
How do I restart speech recognition every 15 seconds?

**Comment by priyaravi20** [comment]
Is there a reason why you want to do that? You can use the dictation mode and have your sessions not endpointed from service side.

**Comment by tftoledo** [comment]
Because after 10-15 seconds of inactivity, recognition is stopped. I needed more continuous recognition.

**Comment by tftoledo** [comment]
One more question: is Dictation ok, however, because in Dictation, is not generated the Current hypothesis?

**Comment by priyaravi20** [comment]
Hi - THis is the expected behavior. The service sends a timeout due to inactivity or silence. You will need to detect this and start another session. Phrase results will be provided within that duration.

**Comment by tftoledo** [comment]
Hi. I understand. The Dictation me useful, however, does not allow me to visualize Current hypothesis that is necessary for my case. So, is there a way to restart Interactive mode every 10-15 seconds??

**Comment by RaviPidaparthi** [comment]
The interactive mode is not built for doing continuous recognition. I would recommend you to use Dictation or Conversation modes for that one. We have it in our roadmap to provide hypothesis support for Dictation and Conversation modes but it is a few months away.

Priya to provide the roadmap for this feature. Assigning to her next.

**Comment by priyaravi20** [comment]
We are working on exposing hypothesis in the next 3 -6 months.
