### ISSUE TITLE
Is it possible to use with Custom Speech Service?

### ISSUE THREAD

**Issue by akidur** [Azure-Samples/SpeechToText-WebSockets-Javascript#19]
hi,
Is it possible to use this with Custom Speech Service? As I undestand for use Custom Speech Service I need to send an Authorization header( "Authorization: "Bearer <token>", I can request a token for this) to connect endpoint. But I'm not finding this method in this API?
Thanks

**Comment by PanosPeriorellis** [comment]
hi akidur,

we are working on this feature in Custom Speech Service, we expect it to be available towards the latter part of the summer.

thanks
Panos

**Comment by akidur** [comment]
Dear Panos,
Thanks for your reply, you mean a feature for using Custom Speech Service with Javascript websocket API or using Custom Speech API with websocket (in any language)?
Which programming language do you recommend to connect to Custom Speech Service via websocket?
Thanks,
Rudi

**Comment by priyaravi20** [comment]
Custom Speech service uses the same SDKs in Bing Speech. JavaScript SDK is not compatible with Custom Speech yet. But will be in summer. Currently you can use C#, Androis, IoS to connect to custom speech.

**Comment by akidur** [comment]
Hi riyaravi20,
Thanks for your reply!
I would like to create a websocket client for the Custom Speech service using a different programming language such as Java, NodeJs, Go. Where can I find some technical information  on how to consume that websocket from  scratch (the expected message, fields, etc)?. I already read the CSS documentation but it focuses on how to use the SDK libraries for C#, javaScript, JavaAndriod. What should I take into account if wanted to create my own SDK for a different language? 
Thanks.

**Comment by priyaravi20** [comment]
You will need to implement https://docs.microsoft.com/en-us/azure/cognitive-services/speech/api-reference-rest/websocketprotocol. But you can only leverage bing speech models and not use custom speech service at this point. After summer the SDK you have developed can be used for custom speech as well.
