### ISSUE TITLE
Nodejs support

### ISSUE THREAD

**Issue by pimente** [Azure-Samples/SpeechToText-WebSockets-Javascript#20]
Hello, thank you for sharing this reference implementation.
Do you plan to officially support nodejs ?
Do you have some unofficial samples to share ?

We tried to run the sample in nodejs with the following modification:
- fix requirejs dependency by following the [requirejs documentation](http://requirejs.org/docs/node.html)
- write a custom `AudioSource` implementing `IAudioSource` and call `SDK.CreateRecognizerWithCustomAudioSource` instead of `SDK.CreateRecognizer`
- require a nodejs socket implementation such as `ws`

The code is running, we manage to authenticate but the server never answers back when we start recognition.

Is it the best approach ?
Thank you for your help

**Comment by RaviPidaparthi** [comment]
The approach sounds right as a starting point. I would recommend you to evaluate all components in common.browser and speech.browser for node.js reimplementation if required.

Its difficult to say what you are missing with out looking at a fiddler trace or your code. To start with can you provide a fiddler trace ? I will be able to point out any protocol gaps.

**Comment by pimente** [comment]
Thank you for the quick reply. 

We are not trying to re-implement the sdk, just trying to make a few changes to make it work with nodejs. These changes should not change how the protocol is handled by the sdk (normally !).

Maybe you can have a look at the simple code bellow and spot some obvious errors ?
If not, we will try to go at a lower lever and debug websocket traces.

Thank you very much !

### nodejs compatible sdk ###

We created a wrapper around the browser sdk to make it compatible for nodejs by following [requirejs documentation](http://requirejs.org/docs/node.html) and requiring a `ws` nodejs websocket implementation:

```js
WebSocket = require('ws');
const requirejs = require('requirejs');
requirejs.config({
    baseUrl: __dirname,
    nodeRequire: require
});
const sdk = requirejs('Speech.Browser.Sdk');
module.exports = sdk;
```

### custom AudioSource ###

We created an implementation of Recorder:

```js
const { Stream } = require('./sdk');

function toArrayBuffer(buf) {
  const ab = new ArrayBuffer(buf.length);
  const view = new Uint8Array(ab);
  for (let i = 0; i < buf.length; ++i) {
    view[i] = buf[i];
  }
  return ab;
}

class Recorder {

    Record(wavStream, outputStream) {
      const callback = (buffer) => outputStream.Write(toArrayBuffer(buffer));
      wavStream.on('data', callback);
      this.mediaResources = { callback, wavStream };
    }

    ReleaseMediaResources() {
      if (this.mediaResources) {
        this.mediaResources.wavStream.removeListener('data', this.mediaResources.callback);
        this.mediaResources = null;
      }
    }
}

module.exports = Recorder;
```
and an implementation of AudioSource sticking as closely to the original source code as possible:
```js
const {
    AudioSourceErrorEvent,
    AudioSourceEvent,
    AudioSourceInitializingEvent,
    AudioSourceOffEvent,
    AudioSourceReadyEvent,
    AudioStreamNodeAttachedEvent,
    AudioStreamNodeAttachingEvent,
    AudioStreamNodeDetachedEvent,
    AudioStreamNodeErrorEvent,
    CreateNoDashGuid,
    Deferred,
    Events,
    EventSource,
    IAudioSource,
    IAudioStreamNode,
    IStringDictionary,
    PlatformEvent,
    Promise,
    PromiseHelper,
    Stream,
    StreamReader,
} = require('./sdk');
const Recorder = require('./recorder');

class AudioSource {

    constructor(wavStream) {
        this.id = CreateNoDashGuid();
        this.events = new EventSource();
        this.recorder = new Recorder();
        this.streams = {};
        this.wavStream = wavStream;
    }

    TurnOn() {
        if (this.initializeDeferral) {
            return this.initializeDeferral.Promise();
        }
        this.initializeDeferral = new Deferred();
        this.OnEvent(new AudioSourceInitializingEvent(this.id)); // no stream id
        this.OnEvent(new AudioSourceReadyEvent(this.id));
        this.initializeDeferral.Resolve(true);
        return this.initializeDeferral.Promise();
    }

    Id() {
        return this.id;
    }

    Attach(audioNodeId) {
        this.OnEvent(new AudioStreamNodeAttachingEvent(this.id, audioNodeId));
        return this.Listen(audioNodeId).OnSuccessContinueWith(
            (streamReader) => {
                this.OnEvent(new AudioStreamNodeAttachedEvent(this.id, audioNodeId));
                return {
                    Detach: () => {
                        streamReader.Close();
                        delete this.streams[audioNodeId];
                        this.OnEvent(new AudioStreamNodeDetachedEvent(this.id, audioNodeId));
                        this.TurnOff();
                    },
                    Id: () => {
                        return audioNodeId;
                    },
                    Read: () => {
                        return streamReader.Read();
                    },
                };
            });
    }

    Detach(audioNodeId) {
        if (audioNodeId && this.streams[audioNodeId]) {
            this.streams[audioNodeId].Close();
            delete this.streams[audioNodeId];
            this.OnEvent(new AudioStreamNodeDetachedEvent(this.id, audioNodeId));
        }
    }

    TurnOff() {
        for (const streamId in this.streams) {
            if (streamId) {
                const stream = this.streams[streamId];
                if (stream) {
                    stream.Close();
                }
            }
        }
        this.recorder.ReleaseMediaResources();
        this.OnEvent(new AudioSourceOffEvent(this.id)); // no stream now
        this.initializeDeferral = null;
        return PromiseHelper.FromResult(true);
    }

    get Events() {
        return this.events;
    }

    /**
     * @private
     */
    Listen(audioNodeId) {
        return this.TurnOn()
            .OnSuccessContinueWith(() => {
                const stream = new Stream(audioNodeId);
                this.streams[audioNodeId] = stream;
                try {
                    this.recorder.Record(this.wavStream, stream);
                } catch (error) {
                    const errorMsg = `Error occured processing the user media stream. ${error}`;
                    this.initializeDeferral.Reject(errorMsg);
                    this.OnEvent(new AudioStreamNodeErrorEvent(this.id, audioNodeId, error));
                }
                return stream.GetReader();
            });
    }

    /**
     * @private
     */
    OnEvent(event) {
        this.events.OnEvent(event);
        Events.Instance.OnEvent(event);
    }
}

module.exports = AudioSource;
```
Anything suspicious ?

**Comment by rjpruitt16** [comment]
Did you ever fix the bug because I am interesting in the same thing @pimente @RaviPidaparthi. If you finish the code, it might be a good idea to open source the nodejs sdk version.

**Comment by pietrop** [comment]
Any news on on this? I'd be super interested in a node js implementation...

**Comment by rjpruitt16** [comment]
I have gotten no response from Microsoft.

**Comment by RaviPidaparthi** [comment]
We currently do not have plans to release a node.js implementation.

**Comment by pietrop** [comment]
Ok thanks for the update @RaviPidaparthi, let us know if that changes in the future. 

@pimente did you have any luck with your implementation? It could be useful to make a github repo for that in the meanwhile, I'd be happy to contribute.

**Comment by c-w** [comment]
There's an unofficial NodeJS client developed by one of my colleagues: https://github.com/michael-chi/BingStt-Websocket. Maybe this will help some people.

**Comment by noopkat** [comment]
I built a more robust version of the above NodeJS client and am sharing it here in case anyone would like to give it a test run for their use case 😄 

https://github.com/noopkat/ms-bing-speech-service

**Comment by priyaravi20** [comment]
Thanks @noopkat and @c-w
