### ISSUE TITLE
Official SDK Repo?

### ISSUE THREAD

**Issue by seanfcarroll** [Azure-Samples/SpeechToText-WebSockets-Javascript#21]
Is this the official repo for the Microsoft Speech to Text SDK or just sample code?

- Is the JS SDK available elsewhere?

- Is it possible it access it via a Microsoft CDN?

**Comment by jawetzel** [comment]
from what i understand since this is a JavaScript SDK, its accessible like most other JavaScript libraries, through the nodeJs CDN using the command they provided: 

npm install microsoft-speech-browser-sdk

nodejs can be found [here](https://nodejs.org/en/)

**Comment by RaviPidaparthi** [comment]
This is the official repo of the javascript sdk. 
You can either install it as an npm package in your repo and reference the js file directly. Or download the files from the distrib folder of the repo and reference. Unfortunately we don't have a CDN today.

**Comment by maddya** [comment]
@RaviPidaparthi is it possible to use that approach to make this work in an Asp.net MVC web app?

**Comment by RaviPidaparthi** [comment]
Yes. This is a vanilla js library. You can use it in any web site/app.
