### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by seanfcarroll** [Azure-Samples/SpeechToText-WebSockets-Javascript#22]
Following the sample code, I am integrating this SDK into a Ruby on Rails app. In the same the Bing Key is accepted via an input. In a real application this would be provided on-page.

Is there some way to protect this key? Eg: Twilio allow a server-side call against the key to return an expiring token, which is then provided to a JS client.

How can I protect the Bing Key?

**Comment by jawetzel** [comment]
Keep your bing key on a server and only serve it over https, that way people could look at the js file and see only a variable where the key is to be stored, instead of the actual key.

**Comment by RaviPidaparthi** [comment]
We support 2 kinds of auth. One is the key based auth which does not provide much security.
The other one is the token based auth described at https://docs.microsoft.com/en-us/azure/cognitive-services/speech/getstarted/getstartedrest#authentication
You can keep the keys on our own service and let the sdk get tokens from your service over https. 

To do this use the CognitiveTokenAuthentication provided by the sdk and implement the callbacks that fetch the token provided by your service.
`SDK.CognitiveTokenAuthentication(fetchCallback, fetchOnExpiryCallback)`
