### ISSUE TITLE
Does not work on OS X Safari

### ISSUE THREAD

**Issue by seanfcarroll** [Azure-Samples/SpeechToText-WebSockets-Javascript#23]
Is this a technical problem or is Safari not supported?

<img width="1236" alt="screen shot 2017-07-05 at 23 02 24" src="https://user-images.githubusercontent.com/11340230/27865705-f4c45cc8-61d6-11e7-9360-b561d18827b7.png">

**Comment by seanfcarroll** [comment]
https://www.quora.com/Why-is-navigator-getUserMedia-not-supported-in-Safari

**Comment by seanfcarroll** [comment]
Ping...

**Comment by priyaravi20** [comment]
Hi Sean - Safari is not supported at present.

**Comment by seanfcarroll** [comment]
<img width="752" alt="screen shot 2017-07-11 at 01 33 17" src="https://user-images.githubusercontent.com/11340230/28026406-4a6fe1c8-65d9-11e7-94e2-dba2dff63784.png">



... no IE support either

**Comment by raaaar** [comment]
Pong. The SDK should work with Safari 11 now. Let us know if it doesn't.
