### ISSUE TITLE
Token Authentication does not work (Uses custom Promise implementation causing exceptions). Please fix and add documentation.

### ISSUE THREAD

**Issue by mattmazzola** [Azure-Samples/SpeechToText-WebSockets-Javascript#25]
First issue is I can't find any official documentation on how to acquire tokens for Cognitive Services on Azure / Microsoft docs.

It is mentioned that it is recommended to keep subscription keys secure in client applications here:
https://docs.microsoft.com/en-us/azure/cognitive-services/speech/getstarted/getstartedjswebsockets

> To work with Bing Speech Recognition API, all you need is a subscription key. However, the Speech API for JavaScript using web socket also support authentication token. If you have an authentication tokan and preferred to use that then do the following. Replace 'let authentication = new SR.CognitiveSubscriptionKeyAuthentication(subscriptionKey);' statement with this 'let authentication = new SR.CognitiveTokenAuthentication(fetchCallback, fetchOnExpiryCallback);'.

However, none of the samples show how to actually use this. Let alone setup an auth service. After searching I found this:
https://blogs.msdn.microsoft.com/data_otaku/2016/11/05/goofing-around-with-the-cognitive-services-translator-api/

Finding this URL: `https://api.cognitive.microsoft.com/sts/v1.0` from the portal was not too bad, but there is nothing that tells you an endpoint called issueToken exists and that it if you POST to it with query parameter of Subscription-key it returns a token string. (Side note: It would be nice if this secure token service returned JSON when the client says Accept: application/json)

**I would suggest to add a specific section in the Cognitive Serivices docs on Authentiation! This is important.**
Since I couldn't get token auth working I had to leave my subscription key in my client app, which someone can steal and abuse, using all my calls per second.

Ok, so I got a node service running that does my token issuing and thought everything was going good.

Then I get to the the part in the sample code which says:
`// Alternatively use SDK.CognitiveTokenAuthentication(fetchCallback, fetchOnExpiryCallback) for token auth`
https://github.com/Azure-Samples/SpeechToText-WebSockets-Javascript/blob/b5ed42600ae587920c7384fac4ba74126ca5b4f7/samples/browser/Sample.html#L91

No where does it say what this call back should return.  I have to look at the source:
`return  this.fetchCallback(authFetchEventId).OnSuccessContinueWith((token: string) => new AuthInfo(AuthHeader, token));`
https://github.com/Azure-Samples/SpeechToText-WebSockets-Javascript/blob/master/src/sdk/speech/CognitiveTokenAuthentication.ts#L24

I see that it is adding a callback that is expecting callback to return a Promise resolving with the token as a string.  However, it's using a non-standard `OnSuccessContinueWith` which does not exist on promises from consumers, hence the error:
`Unhandled callback error: TypeError: _this.fetchCallback(...).OnSuccessContinueWith is not a function`

I would suggest that if you're taking a callback from the user, you should be compatible with promises they will provide which is a standard `then` method.

I see there is a custom promise implementation included in the common library:
https://github.com/Azure-Samples/SpeechToText-WebSockets-Javascript/blob/master/src/common/Promise.ts

~It looks like this is exported so perhaps I can wrap my promise with this but the point is I should not have to. This is implementation detail of the SDK / library.~

Here is what I did to make it work:
```
    const fetchCallback = () => {
      const tokenDeferred = new SDK.Deferred()
      const tokenPromise = this.acquireCognitiveServicesToken()
          .then(token => tokenDeferred.Resolve(token))
      return tokenDeferred.promise
    }
```
The library could easily internalize this Deferred wrapping logic so consumers can pass in regular Promise objects and the still work with the library.

**Comment by priyaravi20** [comment]
Thanks Matt for the detailed feedback. We are working in organizing the documentation for better discovery. Will incorporate your feedback.

**Comment by rcollette** [comment]
Does Microsoft honestly intend to support this product or not?    Two months and no movement on the documentation?

**Comment by priyaravi20** [comment]
We did update the documentation recently and organized the authentication pieces better. Please take a look.
