### ISSUE TITLE
Error compiling when used with Angular 2

### ISSUE THREAD

**Issue by gillouxxx** [Azure-Samples/SpeechToText-WebSockets-Javascript#28]
I am using the api with Angular 2 with several imports.

`import { SpeechConfig, Context, OS, Device, RecognitionMode, SpeechResultFormat } from 'microsoft-speech-browser-sdk/src/sdk/speech/RecognizerConfig';
import { CognitiveSubscriptionKeyAuthentication } from 'microsoft-speech-browser-sdk/src/sdk/speech/CognitiveSubscriptionKeyAuthentication';
import { CreateRecognizer } from 'microsoft-speech-browser-sdk/src/sdk/speech.browser/Exports';`

When the server try to compile the code, their is an error on the PCMRecorder.ts file.

Error:
`D:/Projects/xxxxxxx/web/node_modules/microsoft-speech-browser-sdk/src/common.browser/PCMRecorder.ts (74,45): Property 'close' does not exist on type 'AudioContext'.`

If I comment the line 74, it can compile and everything works fine. Is it possible to have a quick fix ?

**Comment by raaaar** [comment]
`close()` was added to the `AudioContext` type definition relatively recently (https://github.com/Microsoft/TypeScript/commit/8b9fa4ce742), so probably you have a dependency on an outdated version of typescript. Could you take a look at the "lib" section of the _tsconfig.json_ in your project and check the `AudioContextBase` type in the corresponding _d.ts_ file (for instance, "dom" lib would correspond to _node_modules\typescript\lib\lib.dom.d.ts_) to make sure that it has the following line:
```
close(): Promise<void>;
```
If it does not, please update the typescript version in your _project.json_ (e.g., `'"typescript": "~2.3.3"`)

**Comment by gillouxxx** [comment]
Hello,

With typescript 2.3.3, everything works fine. Thanks a lot for your help !!!
