### ISSUE TITLE
Does not work sample with MS Edge 15 and Chrome 60. (403 error)

### ISSUE THREAD

**Issue by osamum** [Azure-Samples/SpeechToText-WebSockets-Javascript#30]
Does not work the following sample with MS Edge 15 and Chrome 60.
https://htmlpreview.github.io/?https://github.com/Azure-Samples/SpeechToText-WebSockets-Javascript/blob/master/samples/browser/Sample.html

I can see the following error using developer tool. (at the time of start button click.)
<img width="781" alt="403error" src="https://user-images.githubusercontent.com/6622532/30575935-19325454-9d3f-11e7-8ecb-617b729320c8.png">

downloaded sample apps behavior is same it too. I using correct subscription key.
Do you know this issue's reason?

**Comment by miparnisari** [comment]
I don't see that error in Edge, but I do this other one:

`Unable to get property 'AudioSource' of undefined or null reference`

**Comment by wolfma61** [comment]
I tried your link 

With my subscription-id on Windows Microsoft Edge 40.15063.0.0
and it worked. 


With my subscription-id with Chrome on Windows
Version 61.0.3163.91 (Official Build) (64-bit)
Version 60..... 64 bit (autoupdated kicked in, can't remember the details)
worked also ...

Wolfgang

**Comment by wolfma61** [comment]
please double check you subscription-id that this is a valid id ...

**Comment by raaaar** [comment]
WRT to checking the subscription key: you could try requesting an auth toke using curl (see the example below) and making sure that it does not fail with 401 or some such.

curl -v -X POST "https://api.cognitive.microsoft.com/sts/v1.0/issueToken" -H "Content-type: application/x-www-form-urlencoded" -H "Content-Length: 0" -H "Ocp-Apim-Subscription-Key: your_subscription_key"

**Comment by osamum** [comment]
I tried your curl command line. The result is my subscription key is correct.
After that, I tried sample app again with same step as yesterday.
The sample did correct work. And local sample too. (why??)
Thank you for your support.

**Comment by raaaar** [comment]
WRT `Unable to get property 'AudioSource' of undefined or null reference`: this is a bug in Sample.html -- RecognizerStop, which takes 2 parameters, is called with only one. Will fix asap.

**Comment by raaaar** [comment]
Should be fixed now.
