### ISSUE TITLE
Safari 11 support

### ISSUE THREAD

**Issue by zifeo** [Azure-Samples/SpeechToText-WebSockets-Javascript#32]
Safari 11 finally ships with WebRTC [support](https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Safari_11_0/Safari_11_0.html). However this does not seem supported out the box by the lib.

**Comment by raaaar** [comment]
Should work now, give it another try.

**Comment by zifeo** [comment]
Sounds good! Thanks.
