### ISSUE TITLE
Speech to text crashes in Safari

### ISSUE THREAD

**Issue by knouse1344** [Azure-Samples/SpeechToText-WebSockets-Javascript#36]
The demo application linked in the documentation (this demo:  https://htmlpreview.github.io/?https://github.com/Azure-Samples/SpeechToText-WebSockets-Javascript/blob/master/samples/browser/Sample.html ) seems to work as expected in Chrome browser, but is crashing in Safari 11.  

Below is a pasted output javascript log, I can't seem to replicate the issue in other browsers and troubleshooting from my end has yielded no results. 

I've looked[ into getUserMedia()](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/getUserMedia) being the issue as a deprecated method but haven't solved the problem.  Any thoughts?

<img width="1670" alt="screen shot 2017-10-04 at 12 00 06 pm" src="https://user-images.githubusercontent.com/1772065/31186239-17a3f1ec-a8fc-11e7-9248-4bd2b950270f.png">

**Comment by raaaar** [comment]
Could you give it another try?

**Comment by knouse1344** [comment]
Oh fantastic, it works.  What did you do?

**Comment by raaaar** [comment]
Compiled ("transpiled") the javascript files and pushed (initial commit only contained fixed in the .ts files).

**Comment by wolfma61** [comment]
closing - please reopen (file a new issue) if necessary

**Comment by Waynewil** [comment]
Just to clarify, if I use this in a web app, will the speech-to-text functionality work in Safari on my iphone and iPad?

**Comment by knouse1344** [comment]
Someone correct me if I'm wrong, but I believe this functionality does **not** work on mobile devices (phone and tablet).  Only browsers (including safari) on desktop/laptop.

**Comment by Waynewil** [comment]
I'm certainly no expert, as I'm a backend database/BI guy, but I did just successfully use the sample page on my iPad (IOS 11.xxx) and it worked perfectly.

**Comment by knouse1344** [comment]
really?  well, that's actually awesome to hear.   I figured it was hardware or OS limited.  I guess not!

**Comment by Waynewil** [comment]
I think the IOS 11 update, which I just applied to all my devices, made all the difference.
