### ISSUE TITLE
Getting 403

### ISSUE THREAD

**Issue by ankitbko** [Azure-Samples/SpeechToText-WebSockets-Javascript#38]
Getting below error when using the sample. I have double checked the subscription key. Along with the sample, my bot (botframework uses this library) and one of our other application is also throwing same error.

![image](https://user-images.githubusercontent.com/3169316/31306110-9fcca656-ab66-11e7-96ae-324603530790.png)

**Comment by priyaravi20** [comment]
Sorry about that @ankitbko . We are looking into the issue and will post an update.

**Comment by anilvem1** [comment]
+1. Can repro the same issue at my end.

**Comment by priyaravi20** [comment]
Can you please retry. We are trying to rootcause this but seems to be working now.

**Comment by anilvem1** [comment]
Hi Priya, we are still getting the same error. Workaround is to clear the browser cache and try again each time for a new session.

**Comment by ankitbko** [comment]
@priyaravi20 sorry for late response. It seems to be working well since yesterday. Thanks for the support.

**Comment by caltv** [comment]
I'm seeing this 403 error...

`WebsocketMessageAdapter.ts:81 WebSocket connection to 'wss://speech.platform.bing.com/speech/recognition/interactive/cognitiveservices/v1?format=simple&language=en-US&Ocp-Apim-Subscription-Key=4cf07b8c1bd540a0be258aaa7dfb7e24&X-ConnectionId=BBC0B7F23D64400D836D89F3718E8BC3' failed: Error during WebSocket handshake: Unexpected response code: 403`

**Comment by zhouwangzw** [comment]
This is because the subscription key or authorization token was invalid.
