### ISSUE TITLE
RuntimeError: Cannot read property 'PlatformEvent' of undefined (Ionic/Typescript)

### ISSUE THREAD

**Issue by david-schopf** [Azure-Samples/SpeechToText-WebSockets-Javascript#40]
When I use the package in Ionic (with TypeScript) and I get a "Runtime Error: cannot read property 'PlatformEvent' of undefined"

I have the following environment:
Ionic Framework: 3.7.1
Ionic App Scripts: 3.0.0
Angular Core: 4.4.3
Angular Compiler CLI: 4.4.3
Node: 8.1.2
OS Platform: macOS Sierra

My imports are:

import 'microsoft-speech-browser-sdk';
import * as SDK from 'Speech.Browser.Sdk';
import {Recognizer} from 'Speech.Browser.Sdk';

Anybody with the same error? Any ideas?

**Comment by raaaar** [comment]
Take a look at #37
