### ISSUE TITLE
Does not work with MediaDevices.getUserMedia, therefore iOS is not supported

### ISSUE THREAD

**Issue by catcher-in-the-try** [Azure-Samples/SpeechToText-WebSockets-Javascript#45]
I want to use the Bing Speech to Text in a browser on an iOS device, which supports `MediaDevices.getUserMedia`. However, this implementation still uses `navigator.getUserMedia`, which means it won't work.

When could I expect the `MediaDevices.getUserMedia` support to be implemented? Thanks.

**Comment by skirunman** [comment]
From a quick look this does not look like a big deal as I could only find 3 instances to fix starting at https://github.com/Azure-Samples/SpeechToText-WebSockets-Javascript/blob/a75e796bc98088cb887e5a3d47e013c2365d6dc8/src/common.browser/MicAudioSource.ts#L61

https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia

**Comment by raaaar** [comment]
Should work now, give it a try.
