### ISSUE TITLE
Using authentication token rather than subscription key to authenticate

### ISSUE THREAD

**Issue by aidangarnish** [Azure-Samples/SpeechToText-WebSockets-Javascript#46]
Can anyone help with an example of how to get and use an authentication token using the SDK?

There is a comment in sample.html:

 // Alternatively use SDK.CognitiveTokenAuthentication(fetchCallback, fetchOnExpiryCallback) for token auth

What should the fetchCallBack and fetchOnExpiryCallback methods look like?

**Comment by raaaar** [comment]
Well, the original idea was that requesting tokens should be implemented out-of-band, by calling https://api.cognitive.microsoft.com/sts/v1.0/issueToken (more info [here](https://docs.microsoft.com/en-us/azure/cognitive-services/speech/how-to/how-to-authentication?tabs=curl)). 
For instance, you can set up a backend service that would respond to the "get-token" requests from your front-end, and in the fetchCallBack/fetchOnExpiryCallback you would basically call this service.

**Comment by raaaar** [comment]
Added [sample-server.js](https://github.com/Azure-Samples/SpeechToText-WebSockets-Javascript/blob/master/samples/browser/sample-server.js) that responds to such requests, updated Sample.html to use token based authentication.
