### ISSUE TITLE
The "Interative" mode can't deal with the long wav in the SDK

### ISSUE THREAD

**Issue by HintDf** [Azure-Samples/SpeechToText-WebSockets-Javascript#47]
I used Sample.html demo to generate the transcript from a 30s wav in Interative mode, but it only return first several secs transcription. BTW, the other two mode works.

**Comment by raaaar** [comment]
The interactive mode is meant to be used with short utterances (2-3 seconds), as soon as there's a silence longer than a timeout interval, the recognition session is terminated. More details here: https://docs.microsoft.com/en-us/azure/cognitive-services/speech/concepts#intercative-mode
