### ISSUE TITLE
Sample.html has a dependency issue

### ISSUE THREAD

**Issue by rangv** [Azure-Samples/SpeechToText-WebSockets-Javascript#5]
<script src="//cdnjs.cloudflare.com/ajax/libs/require.js/2.3.3/require.min.js"></script>

This should be 
    <script src="http:////cdnjs.cloudflare.com/ajax/libs/require.js/2.3.3/require.min.js"></script>

**Comment by RaviPidaparthi** [comment]
I will update the sample to work from disk, http and https. Looks like the current reference is not working if the sample is loaded from disk.

**Comment by RaviPidaparthi** [comment]
This is fixed. And for future reference it is recommended to load the sample on https domain. Not all browsers support microphone access on un-secure domains. 

I added a section in readme to clarify this along with a link to the sample which you can just try out in browser with out having to host the sample yourself..
