### ISSUE TITLE
Please provide doc specification for speech.context

### ISSUE THREAD

**Issue by changkun** [Azure-Samples/SpeechToText-WebSockets-Javascript#50]
https://github.com/Azure-Samples/SpeechToText-WebSockets-Javascript/blob/1717bbd6667a6898c87d462ea6b8dc5d3baf79aa/src/sdk/speech/Recognizer.ts#L246

This function sends speech context whereas the official [doc](https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/cognitive-services/Speech/API-Reference-REST/websocketprotocol.md) of WebSocket doesn't provide this information regarding the format of `speechContextJson`.

Please provide this information to support our development.

**Comment by raaaar** [comment]
Isn't [this](https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/cognitive-services/Speech/API-Reference-REST/websocketprotocol.md#message-payload) what you're looking for?

**Comment by changkun** [comment]
This is not a proper information.

You are providing specification for speech.config, instead of speech.context.

**Comment by raaaar** [comment]
Sorry, my mistake. Speech.context allows to specify dynamic grammar information which affects the lexicon used for recognition by the speech service. However, this feature has not been officially exposed/published. Please ignore for now.
