### ISSUE TITLE
tsc error

### ISSUE THREAD

**Issue by AmarPotki** [Azure-Samples/SpeechToText-WebSockets-Javascript#53]
I'm trying using microsoft-speech-browser-sdk in Typescript
but when I import it I get this error 

> error TS2306: File /node_modules/microsoft-speech-browser-sdk/distrib/speech.browser.sdk.d.ts' is not a module.

I changed the address to 'microsoft-speech-browser-sdk/Speech.Browser.Sdk'
but I got another error 

>  Error - [webpack] 'dist':
./lib/webparts/helloGraph/components/HelloGraph.js
Module not found: Error: Can't resolve 'microsoft-speech-browser-sdk/Speech.Browser.Sdk' in 'D:\Projects\Mine\SPFX\hellograph-webpart\lib\webparts\helloGraph\components'
resolve 'microsoft-speech-browser-sdk/Speech.Browser.Sdk' in 'D:\Projects\Mine\SPFX\hellograph-webpart\lib\webparts\helloGraph\components'
  Parsed request is a module
  using description file: D:\Projects\Mine\SPFX\hellograph-webpart\package.json (relative path: ./lib/webparts/helloGraph/components)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: D:\Projects\Mine\SPFX\hellograph-webpart\package.json (relative path: ./lib/webparts/helloGraph/components)
    resolve as module
      D:\Projects\Mine\SPFX\hellograph-webpart\lib\webparts\helloGraph\components\node_modules doesn't exist or is not a directory
      D:\Projects\Mine\SPFX\hellograph-webpart\lib\webparts\helloGraph\components\lib doesn't exist or is not a directory
      D:\Projects\Mine\SPFX\hellograph-webpart\lib\webparts\helloGraph\node_modules doesn't exist or is not a directory
      D:\Projects\Mine\SPFX\hellograph-webpart\lib\webparts\helloGraph\lib doesn't exist or is not a directory
      D:\Projects\Mine\SPFX\hellograph-webpart\lib\webparts\node_modules doesn't exist or is not a directory
      D:\Projects\Mine\SPFX\hellograph-webpart\lib\webparts\lib doesn't exist or is not a directory
      D:\Projects\Mine\SPFX\hellograph-webpart\lib\node_modules doesn't exist or is not a directory
      D:\Projects\Mine\SPFX\hellograph-webpart\lib\lib doesn't exist or is not a directory
      D:\Projects\Mine\SPFX\node_modules doesn't exist or is not a directory
      D:\Projects\Mine\SPFX\lib doesn't exist or is not a directory
      D:\Projects\Mine\node_modules doesn't exist or is not a directory
      D:\Projects\Mine\lib doesn't exist or is not a directory
      D:\Projects\node_modules doesn't exist or is not a directory
      D:\Projects\lib doesn't exist or is not a directory
      D:\node_modules doesn't exist or is not a directory
      D:\lib doesn't exist or is not a directory
      looking for modules in D:\Projects\Mine\SPFX\hellograph-webpart\node_modules
        using description file: D:\Projects\Mine\SPFX\hellograph-webpart\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: D:\Projects\Mine\SPFX\hellograph-webpart\package.json (relative path: ./node_modules)
          using description file: D:\Projects\Mine\SPFX\hellograph-webpart\node_modules\microsoft-speech-browser-sdk\package.json (relative path: ./Speech.Browser.Sdk)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              D:\Projects\Mine\SPFX\hellograph-webpart\node_modules\microsoft-speech-browser-sdk\Speech.Browser.Sdk doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              D:\Projects\Mine\SPFX\hellograph-webpart\node_modules\microsoft-speech-browser-sdk\Speech.Browser.Sdk.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              D:\Projects\Mine\SPFX\hellograph-webpart\node_modules\microsoft-speech-browser-sdk\Speech.Browser.Sdk.json doesn't exist
            as directory
              D:\Projects\Mine\SPFX\hellograph-webpart\node_modules\microsoft-speech-browser-sdk\Speech.Browser.Sdk doesn't exist
      looking for modules in D:\Projects\Mine\SPFX\hellograph-webpart\lib
        using description file: D:\Projects\Mine\SPFX\hellograph-webpart\package.json (relative path: ./lib)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: D:\Projects\Mine\SPFX\hellograph-webpart\package.json (relative path: ./lib)
          using description file: D:\Projects\Mine\SPFX\hellograph-webpart\package.json (relative path: ./lib/microsoft-speech-browser-sdk/Speech.Browser.Sdk)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              D:\Projects\Mine\SPFX\hellograph-webpart\lib\microsoft-speech-browser-sdk\Speech.Browser.Sdk doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              D:\Projects\Mine\SPFX\hellograph-webpart\lib\microsoft-speech-browser-sdk\Speech.Browser.Sdk.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              D:\Projects\Mine\SPFX\hellograph-webpart\lib\microsoft-speech-browser-sdk\Speech.Browser.Sdk.json doesn't exist
            as directory
              D:\Projects\Mine\SPFX\hellograph-webpart\lib\microsoft-speech-browser-sdk\Speech.Browser.Sdk doesn't exist
[D:\Projects\Mine\SPFX\hellograph-webpart\lib\webparts\helloGraph\components\node_modules]
[D:\Projects\Mine\SPFX\hellograph-webpart\lib\webparts\helloGraph\components\lib]
[D:\Projects\Mine\SPFX\hellograph-webpart\lib\webparts\helloGraph\node_modules]
[D:\Projects\Mine\SPFX\hellograph-webpart\lib\webparts\helloGraph\lib]
[D:\Projects\Mine\SPFX\hellograph-webpart\lib\webparts\node_modules]
[D:\Projects\Mine\SPFX\hellograph-webpart\lib\webparts\lib]
[D:\Projects\Mine\SPFX\hellograph-webpart\lib\node_modules]
[D:\Projects\Mine\SPFX\hellograph-webpart\lib\lib]
[D:\Projects\Mine\SPFX\node_modules]
[D:\Projects\Mine\SPFX\lib]
[D:\Projects\Mine\node_modules]
[D:\Projects\Mine\lib]
[D:\Projects\node_modules]
[D:\Projects\lib]
[D:\node_modules]
[D:\lib]
[D:\Projects\Mine\SPFX\hellograph-webpart\node_modules\microsoft-speech-browser-sdk\Speech.Browser.Sdk]
[D:\Projects\Mine\SPFX\hellograph-webpart\node_modules\microsoft-speech-browser-sdk\Speech.Browser.Sdk.js]
[D:\Projects\Mine\SPFX\hellograph-webpart\lib\microsoft-speech-browser-sdk\Speech.Browser.Sdk]
[D:\Projects\Mine\SPFX\hellograph-webpart\node_modules\microsoft-speech-browser-sdk\Speech.Browser.Sdk.json]
[D:\Projects\Mine\SPFX\hellograph-webpart\lib\microsoft-speech-browser-sdk\Speech.Browser.Sdk.js]
[D:\Projects\Mine\SPFX\hellograph-webpart\node_modules\microsoft-speech-browser-sdk\Speech.Browser.Sdk]
[D:\Projects\Mine\SPFX\hellograph-webpart\lib\microsoft-speech-browser-sdk\Speech.Browser.Sdk.json]
[D:\Projects\Mine\SPFX\hellograph-webpart\lib\microsoft-speech-browser-sdk\Speech.Browser.Sdk]
 @ ./lib/webparts/helloGraph/components/HelloGraph.js 16:27-85
 @ ./lib/webparts/helloGraph/HelloGraphWebPart.js

pls let me know how to use it

**Comment by rcollette** [comment]
Have a look at #37 although I still consider that a workaround.  In the end I've used Webpack/typescript and imported from source rather than using the single library file.

**Comment by AmarPotki** [comment]
@rcollette thx for reply
I want to use microsoft-speech-browser-sdk in SharePoint framework/react and gulp

**Comment by salvoravida** [comment]
try this 
https://github.com/Azure-Samples/SpeechToText-WebSockets-Javascript/pull/52

**Comment by AmarPotki** [comment]
@salvoravida 
pls guide me how to use it

**Comment by salvoravida** [comment]
Hi @AmarPotki 
tu use my pr with just npm you have to wait to pr accept.

**Comment by raaaar** [comment]
Should work now, give it another try. kudos to @salvoravida
