### ISSUE TITLE
Start button disabled in Safari

### ISSUE THREAD

**Issue by rangv** [Azure-Samples/SpeechToText-WebSockets-Javascript#6]
Code had to be changed from
        let startBtn, stopBtn, hypothesisDiv, phraseDiv, statusDiv, key, languageOptions, formatOptions;

To 
        var startBtn, stopBtn, hypothesisDiv, phraseDiv, statusDiv, key, languageOptions, formatOptions;

for start button to be enabled

**Comment by RaviPidaparthi** [comment]
I am surprised that you are having issues with let keyword. Will update the sample.

**Comment by RaviPidaparthi** [comment]
This is fixed.
