### ISSUE TITLE
SDK has issues with Safari

### ISSUE THREAD

**Issue by rangv** [Azure-Samples/SpeechToText-WebSockets-Javascript#7]
navigator.mediaDevices.getUserMedia() errors in Safari after start button is clicked

**Comment by rangv** [comment]
navigator.getUserMedia = navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia;

OnEvent — speech.browser.sdk-min.js:12532017-05-11T22:34:52.793Z | t | eventId: A31AE2B5504049C0852ADEA0C36C4E60 | eventTime: 2017-05-11T22:34:52.793Z | eventType: 3 | metadata: {} | audioSourceId: Browser doesnot support getUserMedia. | error:  | Error:  | AudioSourceId: Browser doesnot support getUserMedia. | Metadata: {}

Unhandled callback error: Error: 'Unhandled callback error: 'Unhandled callback error: Browser doesnot support getUserMedia.''. InnerError: 'Unhandled callback error: 'Unhandled callback error: Browser doesnot support getUserMedia.'''

**Comment by miparnisari** [comment]
http://caniuse.com/#feat=stream

**Comment by jawetzel** [comment]
any plans to make the sdk work with es6 for spa usage?

**Comment by RaviPidaparthi** [comment]
Added browser support section to ReadMe. Safari browser does not support WebRTC apis required to access microphone.
