### ISSUE TITLE
cannot connect to CRIS service: HTTP authentication failed; no valid credentials available

### ISSUE THREAD

**Issue by amenglong** [Azure-Samples/SpeechToText-WebSockets-Javascript#71]
Hi team,

Followed the [3 steps](https://docs.microsoft.com/en-us/azure/cognitive-services/custom-speech-service/customspeech-how-to-topics/cognitive-services-custom-speech-use-endpoint#send-requests-by-using-the-speech-protocol) in order to connect to a customized end point.
Just notice in last step besides "gulp build" also had to"gulp bundle" to update **speech.sdk.bundle.js**. (If not, no matter what key, even a wrong key, I insert in "wss://key.api.cris.ai" the service always works..)

But when testing get this error on the web console:

**Firefox:**
![firefox](https://user-images.githubusercontent.com/24521991/36347792-638669cc-149b-11e8-9054-e038b5bda7ed.jpg)

**Chrome:**
![chrome_log](https://user-images.githubusercontent.com/24521991/36347745-19012c9e-149a-11e8-8531-0836462b334f.PNG)

**Edge:**
![image](https://user-images.githubusercontent.com/24521991/36349439-e529ea96-14c1-11e8-8309-ffd5af3ca887.png)

FYI when connecting to standard voice recognition service (wss://speech.platform.bing.com) there is no problem.

What am I doing wrong? Thanks!

**Comment by andreasla** [comment]
Please double-check that the key that the error message shows is really a subscription key for Custom Speech Service and that it is the key associated with your deployment.

Thanks,

Andreas

**Comment by amenglong** [comment]
Yes, this was the problem. Now works :)

As a suggestion on the documentation you guys can mention:
1. gulp bundle
2. CRIS password

Thanks!
