### ISSUE TITLE
how about a step by step on how to run this?

### ISSUE THREAD

**Issue by jhealy** [Azure-Samples/SpeechToText-WebSockets-Javascript#8]
pull and go, and it yacks all over.  thanks...

**Comment by jhealy** [comment]
instructions to wire up are here.  do not start at the GitHub level and expect to find wireup instructions I guess.

**Comment by seanfcarroll** [comment]
Well an installer / startup command would be nice.

**Comment by priyaravi20** [comment]
https://docs.microsoft.com/en-us/azure/cognitive-services/speech/getstarted/getstartedjswebsockets has a getting started for this sample.
