### ISSUE TITLE
Bing Speech API offline

### ISSUE THREAD

**Issue by solidcloudio** [Azure-Samples/SpeechToText-WebSockets-Javascript#80]
<h2>Our services aren't available right now</h2><p>We're working to restore all services as soon as possible. Please check back soon.</p>Ref A: E46EE7F8DE28480E89BA1F908D77D2DC Ref B: PHX01EDGE0217 Ref C: 2018-03-29T15:44:18Z

Been this way for days...  Sigh

**Comment by RaviPidaparthi** [comment]
Just tried the sample and it seems to be working. 
https://htmlpreview.github.io/?https://github.com/Azure-Samples/SpeechToText-WebSockets-Javascript/blob/preview/samples/browser/Sample.html

Can you explain a bit more about the issue ? Is it intermittent or is it down 100% for you ? Are you using our sdk or something else ?

**Comment by solidcloudio** [comment]
Same thing on the sample:

VM45:1629 WebSocket connection to 'wss://speech.platform.bing.com/speech/recognition/interactive/cognitiveservices/v1?format=simple&language=en-US&Ocp-Apim-Subscription-Key=<removed>&X-ConnectionId=60F6B3473678406B8A36ADFC10653807' failed: Error during WebSocket handshake: Unexpected response code: 403

I've tried both the https://github.com/Azure-Samples/Cognitive-Speech-STT-ServiceLibrary and the BotFramework WebControl from <script src="https://cdn.botframework.com/botframework-webchat/latest/CognitiveServices.js"></script>

Maybe its my API key, but I've signed up for a new service in Azure on an EA account so I shouldn't have any "billing restrictions"  I've created an Azure support ticket.

**Comment by RaviPidaparthi** [comment]
403 is authentication error. Please make sure your api key is valid.

**Comment by solidcloudio** [comment]
Doesn't seem to matter what key I use..  Tried regenerating key, changed billing plan to standard..  Same issue no matter what I do.  This was working when the 30 day trial key was used, now that I've moved this to Azure it won't work.

**Comment by solidcloudio** [comment]
Lets see if my Azure support ticket goes anywhere...

**Comment by solidcloudio** [comment]
Able to get this to work by creating a new Cognitive Services resource.  Not sure what the problem was with the previous one, but alas, its working with the new one..
